FROM python

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
ENV APP_HOST=127.0.0.1
ENV APP_PORT=5000
ENV REDIS_HOST=172.19.0.3
ENV REDIS_PORT=6379
ENV DATABASE_URI=mysql+pymysql://root:jeswin@35.87.44.75:3306/test
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
